"""Assemble the blind-tdd plugin's generated artifacts from canonical sources.

Single source of truth lives in ralph-universal: the role prompts in
`templates/blind_tdd/prompts/` and the hook scripts in `templates/hooks/`. This
script derives the plugin's:

  - `agents/blind-{writer,runner,arbiter}.md`  (YAML frontmatter + the prompt body)
  - `hooks/blind_tdd_{path_guard,audit,bash_guard}.py`  (copied verbatim)
  - `requirements.txt`                         (the Themis engine pin)

so the prompt bodies are never hand-duplicated (which would drift). Idempotent;
re-run after editing a prompt.

Engine, not vendored: the orchestration engine (red/green sealing, coverage,
challenge/arbiter) is the standalone **Themis** package
(github.com/dscherm/themis), consumed via pip — never copied into the plugin.
The plugin itself ships only the blindness layer (stdlib hook scripts + agent
defs); `requirements.txt` records the engine dependency so a `/plugin install`
user runs one `pip install` to get the orchestration. This script verifies the
engine is importable at assemble time but does not fold its source in.

Usage:
    python plugin/blind-tdd/assemble.py                 # from ralph-universal root
    python assemble.py --ralph-home /path/to/ralph      # from elsewhere
"""

from __future__ import annotations

import argparse
import importlib.util
import shutil
from pathlib import Path

# The Themis engine dependency, recorded into the plugin's requirements.txt.
# Pip distribution name + git source (matches ralph-universal's own requirements.txt).
ENGINE_DIST = "themis-blind-tdd"
ENGINE_PIN = "themis-blind-tdd @ git+https://github.com/dscherm/themis.git"

# role -> (prompt filename, agent filename, frontmatter dict). `tools` is the
# subagent's allowed-tool whitelist (derived from templates/blind_tdd/settings.blind-*.json).
ROLES = {
    "writer": {
        "prompt": "test_writer.md",
        "agent": "blind-writer.md",
        "name": "blind-writer",
        "model": "sonnet",
        "tools": "Read, Grep, Glob, Write, Edit, WebFetch",
        "description": (
            "Blind TDD test writer (Agent #1): writes failing tests from a task's "
            "acceptance_criteria alone, before any implementation exists. Cannot "
            "read src/ (PreToolUse path-guard blocks it). No Bash."
        ),
    },
    "runner": {
        "prompt": "test_runner.md",
        "agent": "blind-runner.md",
        "name": "blind-runner",
        "model": "sonnet",
        # NOTE: Bash is needed to execute tests, but agent frontmatter cannot
        # express the Bash(pytest*)-only restriction from settings.blind-runner.json.
        # The in-session model therefore REQUIRES a blind_tdd_bash_guard.py hook to
        # block cat/grep/find/etc. while a session is active. See README §Bash guard.
        "tools": "Read, Grep, Glob, Bash",
        "description": (
            "Blind TDD test runner (Agent #2): executes the hash-locked tests and "
            "produces a verified green report. Bash restricted to test commands; "
            "stays blind to implementation via the path-guard + bash-guard hooks."
        ),
    },
    "arbiter": {
        "prompt": "arbiter.md",
        "agent": "blind-arbiter.md",
        "name": "blind-arbiter",
        "model": "opus",
        "tools": "Read, Grep, Glob, WebFetch",
        "description": (
            "Blind TDD arbiter (Agent #3): rules upheld/rejected/ambiguous on a "
            "challenge to a blind test. Read-only; no Bash, no Edit/Write."
        ),
    },
}


def _frontmatter(role_cfg: dict) -> str:
    return (
        "---\n"
        f"name: {role_cfg['name']}\n"
        f"description: {role_cfg['description']}\n"
        f"model: {role_cfg['model']}\n"
        f"tools: {role_cfg['tools']}\n"
        "---\n\n"
        "<!-- GENERATED by plugin/blind-tdd/assemble.py from "
        f"templates/blind_tdd/prompts/{role_cfg['prompt']} — edit the prompt, not this file. -->\n\n"
    )


def assemble(ralph_home: Path, out_dir: Path, prompts_dir: Path | None = None) -> dict:
    """Generate agent defs + copy hooks. Returns a summary dict of what was written."""
    prompts_dir = prompts_dir or (ralph_home / "templates" / "blind_tdd" / "prompts")
    hooks_src = ralph_home / "templates" / "hooks"

    agents_out = out_dir / "agents"
    hooks_out = out_dir / "hooks"
    agents_out.mkdir(parents=True, exist_ok=True)
    hooks_out.mkdir(parents=True, exist_ok=True)

    written_agents: list[str] = []
    for role, cfg in ROLES.items():
        prompt_path = prompts_dir / cfg["prompt"]
        if not prompt_path.exists():
            raise FileNotFoundError(f"prompt missing for role {role!r}: {prompt_path}")
        body = prompt_path.read_text(encoding="utf-8")
        (agents_out / cfg["agent"]).write_text(
            _frontmatter(cfg) + body, encoding="utf-8"
        )
        written_agents.append(cfg["agent"])

    copied_hooks: list[str] = []
    for script in ("blind_tdd_path_guard.py", "blind_tdd_audit.py", "blind_tdd_bash_guard.py"):
        src = hooks_src / script
        if not src.exists():
            raise FileNotFoundError(f"hook script missing: {src}")
        shutil.copy2(src, hooks_out / script)
        copied_hooks.append(script)

    # Record the engine dependency (pip-installed Themis), never vendor it.
    reqs_path = out_dir / "requirements.txt"
    reqs_path.write_text(
        "# The blind-TDD orchestration engine is the standalone Themis package.\n"
        "# It is consumed via pip, never vendored into this plugin.\n"
        "# Repo: https://github.com/dscherm/themis\n"
        f"{ENGINE_PIN}\n",
        encoding="utf-8",
    )

    # Best-effort: confirm the engine is importable in this environment. A miss
    # leaves the plugin's blindness layer intact but its gate inert until the
    # user runs `pip install -r requirements.txt` — surfaced, not fatal.
    engine_importable = importlib.util.find_spec("blind_tdd") is not None

    return {
        "agents": written_agents,
        "hooks": copied_hooks,
        "requirements": reqs_path.name,
        "engine": {"dist": ENGINE_DIST, "importable": engine_importable},
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Assemble the blind-tdd plugin artifacts.")
    ap.add_argument("--ralph-home", default=None,
                    help="ralph-universal root (default: two levels up from this script)")
    ap.add_argument("--out-dir", default=None,
                    help="plugin dir to write into (default: this script's dir)")
    ap.add_argument("--prompts-dir", default=None,
                    help="override the role-prompts source dir")
    ns = ap.parse_args(argv)

    here = Path(__file__).resolve()
    ralph_home = Path(ns.ralph_home).resolve() if ns.ralph_home else here.parents[2]
    out_dir = Path(ns.out_dir).resolve() if ns.out_dir else here.parent
    prompts_dir = Path(ns.prompts_dir).resolve() if ns.prompts_dir else None

    summary = assemble(ralph_home, out_dir, prompts_dir)
    print(f"assembled agents: {summary['agents']}")
    print(f"copied hooks:     {summary['hooks']}")
    print(f"engine pin:       {summary['requirements']} -> {ENGINE_DIST}")
    if not summary["engine"]["importable"]:
        print(f"  WARNING: {ENGINE_DIST} is not importable here. The plugin's "
              "blindness layer is assembled, but the gate stays inert until "
              "`pip install -r requirements.txt`.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
