"""Tests for the blind-tdd plugin assembler (agent defs generated from prompts)."""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

_HERE = Path(__file__).resolve()
sys.path.insert(0, str(_HERE.parent))

import assemble as asm  # noqa: E402

_RALPH_HOME = _HERE.parents[2]  # plugin/blind-tdd/ -> repo root


def test_assemble_writes_agents_and_hooks(tmp_path):
    summary = asm.assemble(_RALPH_HOME, tmp_path)
    assert summary["agents"] == ["blind-writer.md", "blind-runner.md", "blind-arbiter.md"]
    assert summary["hooks"] == [
        "blind_tdd_path_guard.py", "blind_tdd_audit.py", "blind_tdd_bash_guard.py",
    ]
    for name in summary["agents"]:
        assert (tmp_path / "agents" / name).exists()
    for name in summary["hooks"]:
        h = tmp_path / "hooks" / name
        assert h.exists() and h.stat().st_size > 0


def test_assemble_writes_engine_requirements(tmp_path):
    summary = asm.assemble(_RALPH_HOME, tmp_path)
    assert summary["requirements"] == "requirements.txt"
    reqs = tmp_path / "requirements.txt"
    assert reqs.exists()
    text = reqs.read_text(encoding="utf-8")
    assert asm.ENGINE_PIN in text
    assert "github.com/dscherm/themis" in text
    # engine is recorded as a pip dependency, not vendored as source
    assert summary["engine"]["dist"] == "themis-blind-tdd"
    assert not list(tmp_path.rglob("orchestrator.py"))
    assert not list(tmp_path.rglob("gate_integration.py"))


def test_writer_frontmatter_and_body(tmp_path):
    asm.assemble(_RALPH_HOME, tmp_path)
    text = (tmp_path / "agents" / "blind-writer.md").read_text(encoding="utf-8")
    assert text.startswith("---\n")
    assert "name: blind-writer" in text
    assert "model: sonnet" in text
    assert "tools: Read, Grep, Glob, Write, Edit, WebFetch" in text
    assert "GENERATED by plugin/blind-tdd/assemble.py" in text
    # body of the canonical prompt is included verbatim
    assert "# Blind TDD — Test Writer Agent (Agent #1)" in text


def _tools_line(text: str) -> str:
    for line in text.splitlines():
        if line.startswith("tools:"):
            return line
    return ""


def test_runner_has_bash_arbiter_does_not(tmp_path):
    asm.assemble(_RALPH_HOME, tmp_path)
    runner = (tmp_path / "agents" / "blind-runner.md").read_text(encoding="utf-8")
    arbiter = (tmp_path / "agents" / "blind-arbiter.md").read_text(encoding="utf-8")
    assert "Bash" in _tools_line(runner)
    assert "model: opus" in arbiter
    assert "Bash" not in _tools_line(arbiter)


def test_every_role_can_write_its_report(tmp_path):
    """Regression: each blind role's frontmatter must grant Write so it can emit
    its mandated output (triage / green_report / ruling). A live run found the
    runner and arbiter grants missing Write, leaving the agent no tool for its
    report. This asserts the plugin surface, mirroring test_role_settings for
    the engine settings surface."""
    asm.assemble(_RALPH_HOME, tmp_path)
    for agent in ("blind-writer", "blind-runner", "blind-arbiter"):
        text = (tmp_path / "agents" / f"{agent}.md").read_text(encoding="utf-8")
        assert "Write" in _tools_line(text), f"{agent}: frontmatter tools grant omits Write"


def test_missing_prompt_dir_raises(tmp_path):
    with pytest.raises(FileNotFoundError):
        asm.assemble(_RALPH_HOME, tmp_path, prompts_dir=tmp_path / "nope")


def test_idempotent(tmp_path):
    asm.assemble(_RALPH_HOME, tmp_path)
    first = (tmp_path / "agents" / "blind-writer.md").read_text(encoding="utf-8")
    asm.assemble(_RALPH_HOME, tmp_path)
    second = (tmp_path / "agents" / "blind-writer.md").read_text(encoding="utf-8")
    assert first == second
